apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-stack
  namespace: flux-system
spec:
  interval: 1h
  path: "./infrastructure/forgejo"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
