apiVersion: v1
kind: Service
metadata:
  name: forgejo-db
  labels:
    app: forgejo-db
spec:
  type: ClusterIP
  selector:
    app: forgejo-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
