apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-gitrepository.yaml
  - flux-webhook-secret.yaml
  - flux-receiver.yaml
  - flux-provider-tekton.yaml
  - flux-alert-tekton.yaml
  - tekton-triggers-rbac.yaml
  - task-dagger-pipeline.yaml
  - pipeline-dagger.yaml
  - trigger-binding-flux.yaml
  - trigger-template-dagger.yaml
  - event-listener-flux.yaml
